name: Build Check and Deploy Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - foxy

jobs:
  deploy-multiversion:
    name: Deploy Multiversion
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        cd docs/
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
    - name: Build multiversion
      run: |
        cd docs/
        make multiversion
    - name: Deploy Pages
      if: ${{ success() }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        cname: rtw.stoglrobotics.de
